name: "Publish Website"
concurrency: 
  group: website
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      publish_type:
        description: "Select what to build. Defaults to 'website'"
        required: true
        default: 'website' 
        type: choice
        options:
        - 'website'
        - 'docs'
jobs:
  website:
    uses: naev/naev-infrastructure/.github/workflows/website_build.yml@main
    if: github.event.inputs.publish_type == 'website'
    with:
      publish_type: ${{ github.event.inputs.publish_type }}
  docs:
    uses: naev/naev-infrastructure/.github/workflows/website_build.yml@main
    if: github.event.inputs.publish_type == 'docs'
    with:
      publish_type: ${{ github.event.inputs.publish_type }}
