name: "Publish Website"
on:
  workflow_dispatch:
    inputs:
      publish_type:
        description: "'website' for website build, and 'api' for API build"
        required: true
        type: string
jobs:
  website:
    uses: naev/naev.github.io/.github/workflows/website_publish.yml@main
    if: github.event.inputs.publish_type == 'website'
    with:
      publish_type: ${{ github.event.inputs.publish_type }}
  api:
    uses: naev/naev.github.io/.github/workflows/website_publish.yml@main
    if: github.event.inputs.publish_type == 'api'
    with:
      publish_type: ${{ github.event.inputs.publish_type }}